# Classes
module Platformer
  module Databases
    self.@servers: {
      postgres: Hash[Symbol, Postgres::Server]
    }

    def self.server: (Symbol server_type, Symbol server_name) -> Postgres::Server
    def self.clear_configuration: -> void
    def self.servers: (Symbol server_type) -> Array[Postgres::Server]

    class UnexpectedServerTypeError < StandardError
    end

    class NoDatabaseServersError < StandardError
    end

    class NoDatabaseServersOfThisTypeError < StandardError
    end

    class ExpectedSymbolError < StandardError
    end
  end
end