# frozen_string_literal: true

ruby "~> 3.0"

source "https://rubygems.org"

gem "platformer", "~> 0.0.0"

# Use Puma as the app server
gem "puma", "~> 3.7"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end
