# Classes
module Platformer
  module Databases
    class Migrations
      @base_path: untyped
      @current_migrations: untyped
      @loader: bot

      def initialize: (untyped base_path) -> void
      def generate_migration_files: () -> void

      private
      def current: -> Current
      def load_database_structure: -> untyped
    end
  end
end
