# frozen_string_literal: true

# Projects which use the platformer gem include this file in their Rakefile
# This Rakefile is not used for the platformer gem itself, if you want to add
# tasks for development, then they should go in the Rakefile at the root of this
# repository.

require "platformer"

path = File.expand_path(__dir__)
Dir.glob("#{path}/platformer/tasks/**/*.rake").each { |f| import f }
