# this file is used by the test suite to connect to the database
postgres:
  primary:
    default_database: platformer_test
    username: specs_user
    password: specs_password
    host: localhost
    port: 5432
