name: Specs

on:
  push:
    branches:
      - "*"

jobs:
  specs:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: specs_user
          POSTGRES_PASSWORD: specs_password
          POSTGRES_DB: platformer_migrations
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

      # Checkout code
      - uses: actions/checkout@v3

      # Setup ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      # Bundle install
      - run: bundle install

      # move the database configuration into place
      - name: Move database configuration file
        run: mv config/database.ci.yaml config/database.yaml

      # run the tests
      - name: Run rspec test suite
        run: bundle exec rspec
